=== mowgliLab/json-s-gen/test/files/assert-full-schema.json
{
  "$id": "http://example.com/example.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "checked": {
      "$id": "/properties/checked",
      "type": "boolean",
      "title": "The Checked Schema ",
      "default": false,
      "examples": [
        false
      ]
    },
    "dimensions": {
      "$id": "/properties/dimensions",
      "type": "object",
      "properties": {
        "width": {
          "$id": "/properties/dimensions/properties/width",
          "type": "integer",
          "title": "The Width Schema ",
          "default": 0
        },
        "height": {
          "$id": "/properties/dimensions/properties/height",
          "type": "integer",
          "title": "The Height Schema ",
          "default": 0,
          "examples": [
            10
          ]
        }
      }
    },
    "id": {
      "$id": "/properties/id",
      "type": "integer",
      "title": "The Id Schema ",
      "default": 0,
      "examples": [
        1
      ]
    },
    "name": {
      "$id": "/properties/name",
      "type": "string",
      "title": "The Name Schema ",
      "default": "",
      "examples": [
        "A green door"
      ]
    },
    "price": {
      "$id": "/properties/price",
      "type": "number",
      "title": "The Price Schema ",
      "default": 0,
      "examples": [
        12.5
      ]
    },
    "tags": {
      "$id": "/properties/tags",
      "type": "array",
      "items": {
        "$id": "/properties/tags/items",
        "type": "string",
        "title": "The 0th Schema ",
        "default": "",
        "examples": [
          "home",
          "green"
        ]
      }
    },
    "person": {
      "$id": "/properties/person",
      "type": "object",
      "properties": {
        "firstname": {
          "$id": "/properties/person/properties/firstname",
          "type": "string",
          "title": "The Firstname Schema ",
          "default": "",
          "examples": [
            "Marcel"
          ]
        },
        "lastname": {
          "$id": "/properties/person/properties/lastname",
          "type": "string",
          "title": "The Lastname Schema ",
          "default": "",
          "examples": [
            "Durant"
          ]
        },
        "address": {
          "$id": "/properties/person/properties/address",
          "type": "object",
          "properties": {
            "street": {
              "$id": "/properties/person/properties/address/properties/street",
              "type": "string",
              "title": "The Street Schema ",
              "default": "",
              "examples": [
                "rue du couvent"
              ]
            },
            "number": {
              "$id": "/properties/person/properties/address/properties/number",
              "type": "integer",
              "title": "The Number Schema ",
              "default": 0,
              "examples": [
                "rue du couvent"
              ]
            }
          }
        }
      }
    }
  }
}

=== mowgliLab/json-s-gen/test/files/full.json
{
  "checked": false,
  "dimensions": {
    "width": 5,
    "height": 10
  },
  "id": 1,
  "name": "A green door",
  "price": 12.5,
  "tags": [
    "home",
    "green"
  ],
  "person": {
    "firstname": "Marcel",
    "lastname": "Durant",
    "address": {
      "street": "rue du couvent",
      "number": 4
    }
  }
}
